/**
 * EvaluationMemo - Builder for evaluation memos
 */

export interface MemoSection {
  title: string;
  content: string;
  priority: 'low' | 'medium' | 'high';
}

export interface EvaluationMemo {
  id: string;
  title: string;
  brief: string;
  sections: MemoSection[];
  finalVerdict: 'approve' | 'revise' | 'reject';
  score: number;
  generatedBy: string;
  createdAt: string;
}

export interface MemoSummary {
  totalEvaluations: number;
  approveRate: number;
  avgScore: number;
  commonIssues: string[];
}

export class EvaluationMemoBuilder {
  private title?: string;
  private brief?: string;
  private sections: MemoSection[] = [];
  private verdict?: 'approve' | 'revise' | 'reject';
  private score?: number;
  private generatedBy?: string;

  setTitle(title: string): this {
    this.title = title;
    return this;
  }

  setBrief(brief: string): this {
    this.brief = brief;
    return this;
  }

  addSection(title: string, content: string, priority: 'low' | 'medium' | 'high' = 'medium'): this {
    this.sections.push({ title, content, priority });
    return this;
  }

  setVerdict(verdict: 'approve' | 'revise' | 'reject', score: number): this {
    if (score < 0 || score > 1) {
      throw new Error('Score must be between 0 and 1');
    }
    this.verdict = verdict;
    this.score = score;
    return this;
  }

  setGeneratedBy(agent: string): this {
    this.generatedBy = agent;
    return this;
  }

  build(): EvaluationMemo {
    if (!this.title) {
      throw new Error('EvaluationMemo requires a title');
    }
    if (!this.brief) {
      throw new Error('EvaluationMemo requires a brief');
    }
    if (!this.verdict || this.score === undefined) {
      throw new Error('EvaluationMemo requires a verdict and score');
    }
    if (!this.generatedBy) {
      throw new Error('EvaluationMemo requires generatedBy');
    }

    return {
      id: `memo-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      title: this.title,
      brief: this.brief,
      sections: this.sections,
      finalVerdict: this.verdict,
      score: this.score,
      generatedBy: this.generatedBy,
      createdAt: new Date().toISOString(),
    };
  }
}

export function formatMemo(memo: EvaluationMemo): string {
  const sections = memo.sections
    .map((s) => `## ${s.title} (${s.priority})\n\n${s.content}`)
    .join('\n\n');

  return `# ${memo.title}

**Verdict:** ${memo.finalVerdict.toUpperCase()} (score: ${memo.score.toFixed(2)})

${memo.brief}

${sections}

---
Generated by: ${memo.generatedBy}
`;
}

export function summarizeMemos(memos: EvaluationMemo[]): MemoSummary {
  if (memos.length === 0) {
    return {
      totalEvaluations: 0,
      approveRate: 0,
      avgScore: 0,
      commonIssues: [],
    };
  }

  const approved = memos.filter((m) => m.finalVerdict === 'approve').length;
  const avgScore = memos.reduce((sum, m) => sum + m.score, 0) / memos.length;

  return {
    totalEvaluations: memos.length,
    approveRate: approved / memos.length,
    avgScore,
    commonIssues: [],
  };
}
