#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-/etc/liminal/living-site.env}"
ENV_DIR="$(dirname "$ENV_FILE")"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run with sudo so the secret file can be root-owned and chmod 600:" >&2
  echo "  sudo $0 ${ENV_FILE}" >&2
  exit 1
fi

umask 077
mkdir -p "$ENV_DIR"

printf "Choose living-site inference provider [minimax/glm]: "
read -r PROVIDER
case "$PROVIDER" in
  minimax)
    BASE_URL="https://api.minimax.io/anthropic"
    MODEL="MiniMax-M2.7"
    KEY_NAME="MINIMAX_API_KEY"
    ;;
  glm)
    BASE_URL="https://api.z.ai/api/anthropic"
    MODEL="GLM-5v-turbo"
    KEY_NAME="GLM_API_KEY"
    ;;
  *)
    echo "Unsupported provider: $PROVIDER" >&2
    exit 1
    ;;
esac

printf "Enter %s (input hidden): " "$KEY_NAME"
read -rs API_KEY
printf "\n"
if [[ -z "$API_KEY" ]]; then
  echo "Refusing to write empty API key." >&2
  exit 1
fi

printf "Enter LIMINAL_POSTHOG_KEY (input hidden, leave blank to skip): "
read -rs POSTHOG_KEY
printf "\n"

TMP_FILE="$(mktemp)"
{
  echo "# Liminal living-site daemon secrets"
  echo "# Generated by scripts/setup-living-site-secrets.sh"
  echo "# Keep this file root-owned and chmod 600. Do not commit."
  echo "LIMINAL_LLM_BASE_URL=${BASE_URL}"
  echo "LIMINAL_LLM_MODEL=${MODEL}"
  echo "${KEY_NAME}=${API_KEY}"
  echo "LIMINAL_ALLOWED_HOSTS=api.minimax.io,api.z.ai,open.bigmodel.cn,bigmodel.cn,puenteworks.com,app.posthog.com"
  echo "LIMINAL_ALLOW_PRIVATE_IP_LLM=false"
  echo "LIMINAL_ALLOW_LOCALHOST_LLM=false"
  if [[ -n "$POSTHOG_KEY" ]]; then
    echo "LIMINAL_POSTHOG_KEY=${POSTHOG_KEY}"
    echo "LIMINAL_POSTHOG_HOST=https://puenteworks.com/ph"
  fi
} > "$TMP_FILE"

install -o root -g root -m 600 "$TMP_FILE" "$ENV_FILE"
rm -f "$TMP_FILE"

echo "Wrote secure env file: $ENV_FILE"
echo "Permissions: $(stat -f '%Sp %Su:%Sg' "$ENV_FILE" 2>/dev/null || stat -c '%A %U:%G' "$ENV_FILE")"
echo "Next: install the systemd unit example and point EnvironmentFile at this path."
